name: Main

on:
  push:
    branches: [master]
  pull_request:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pdm install

      - name: Check format
        run: pdm run black logto samples --check

      - name: Build
        run: pdm build

      - name: Run tests
        run: pdm test
